# Generated by Django 4.0.5 on 2022-06-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('title', models.CharField(db_index=True, max_length=90, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('rate', models.CharField(blank=True, choices=[('1.0', '1 - Very Poor'), ('2.0', '2 - Below Average'), ('3.0', '3 - Average'), ('4.0', '4 - Good'), ('5.0', '5 - Excellent')], default='3.0', max_length=3, null=True, verbose_name='Rate')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Update Date')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('favorites', models.PositiveIntegerField(default=0, verbose_name='Favorites')),
                ('authors', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-create_date'],
            },
        ),
    ]
