# Generated by Django 4.0.5 on 2022-06-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
    ]
