# Generated by Django 4.0.5 on 2022-06-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
    ]
