# Generated by Django 4.0.5 on 2022-06-23 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_remove_article_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='article',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='user_favorited', to=settings.AUTH_USER_MODEL, verbose_name='Favorited by Users'),
        ),
        migrations.AddField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL, verbose_name='Liked by Users'),
        ),
    ]
