# Generated by Django 4.0.5 on 2022-06-23 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_remove_article_favorites_remove_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='article',
            name='favorited',
            field=models.ManyToManyField(related_name='user_favorited', to=settings.AUTH_USER_MODEL, verbose_name='Favorited by Users'),
        ),
        migrations.AlterField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(related_name='user_liked', to=settings.AUTH_USER_MODEL, verbose_name='Liked by Users'),
        ),
    ]
