# Generated by Django 4.0.5 on 2022-06-23 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_alter_article_creator_alter_article_favorited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(blank=[], related_name='user_liked', to=settings.AUTH_USER_MODEL, verbose_name='Liked by Users'),
        ),
    ]
