# Generated by Django 4.0.5 on 2022-06-23 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_alter_article_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favorited',
            field=models.ManyToManyField(default=[], related_name='user_favorited', to=settings.AUTH_USER_MODEL, verbose_name='Favorited by Users'),
        ),
        migrations.AlterField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(default=[], related_name='user_liked', to=settings.AUTH_USER_MODEL, verbose_name='Liked by Users'),
        ),
    ]
