# Generated by Django 4.0.5 on 2022-06-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_category_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=90, verbose_name='Tag')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.tag', verbose_name='Category'),
        ),
    ]
